### ISSUE TITLE
Error running Propanet with example data

### ISSUE THREAD

**Issue by archanabhardwaj** [bhi-kimlab/PropaNet#1]
Hello 
I would like to use PropaNet in my project. I am working on gene expression based time series data.  Based on the instruction, installed python2.7 with all required libraries such as networkx,multiprocessing and scipy.stats. As a test run, preferred to work with example data. But during test run,  I am getting only PropaNet.nwk.t* and PropaNet.DEGli.t* files but ranked files are missing and not able to get the final network. Detail error  information is given below: 
network done
('TF length', 1717)
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t1.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t2.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t3.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t4.trim'
Please help me to sort this issue.

**Comment by edugenetico** [comment]
Hello,
I have had the same problem running PropaNet with the example. It is similar to what happened to archanabhardwa
I put my error:


 bash run.sh                                                                                                                                                                        [10:35]

network done
('TF length', 1717)
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t2.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t1.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t3.trim'
Traceback (most recent call last):
  File "Target_genes.py", line 83, in <module>
    with open(args.DEGfile) as f, open(args.TFfile) as f2:
IOError: [Errno 2] No such file or directory: 'result/intermediate_results/PropaNet.TF_rank.t4.trim'




Could you tell me how to solve it?
I work with Ubuntu 14. thanks
